# ============================================================================
# Cross-Validation: Julia Proxy-SVAR vs Python (Jentsch & Lunsford 2022)
# ============================================================================
# Loads data generated by generate_python_testdata.py and compares
# Julia proxy-SVAR estimates against the Python implementation.
#
# The Python code uses: H1 = Σ_um / φ  where φ = √(Σ_um' Σ_uu⁻¹ Σ_um)
# Julia uses: equation-by-equation 2SLS with unit effect normalization.
# These are equivalent: H1_julia = H1_python / H1_python[1]

using MacroEconometricTools
using Test
using LinearAlgebra
using CSV
using DataFrames

const DATADIR = joinpath(@__DIR__, "data")

@testset "Proxy-SVAR: Python Cross-Validation (Jentsch-Lunsford DGP)" begin

    # ── Load Python data ──────────────────────────────────────────────────
    Y_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_Y.csv"), DataFrame))
    proxy_py = vec(Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_proxy.csv"), DataFrame)))
    eps_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_eps.csv"), DataFrame))

    # Python estimation results
    A_est_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_A_est.csv"), DataFrame; header = false))
    U_est_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_U_est.csv"), DataFrame; header = false))
    covUU_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_covUU.csv"), DataFrame; header = false))
    covUM_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_covUM.csv"), DataFrame; header = false))
    H1_py = vec(Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_H1.csv"), DataFrame; header = false)))
    irf_py = Matrix(CSV.read(joinpath(DATADIR, "jl_crossval_irf.csv"), DataFrame; header = false))

    params_df = CSV.read(joinpath(DATADIR, "jl_crossval_params.csv"), DataFrame)
    params = Dict(row.parameter => row.value for row in eachrow(params_df))

    T = Int(params["T"])
    K = Int(params["K"])
    p = Int(params["p"])
    T_eff = Int(params["T_eff"])

    @test size(Y_py) == (T, K)
    @test size(proxy_py) == (T,)

    # ── Julia estimation ──────────────────────────────────────────────────
    # Proxy aligned with VAR residuals (drop first p observations)
    Z_proxy = reshape(proxy_py[(p + 1):end], :, 1)
    instrument = ExternalInstrument(Z_proxy, 1)

    model = fit(IVSVAR, Y_py, p;
        instrument = instrument, names = [:Y1, :Y2])

    θ_julia = model.metadata.iv_coefficients
    ν_julia = residuals(model)

    # ── Test 1: VAR coefficients match ────────────────────────────────────
    @testset "VAR coefficients match Python" begin
        # Python A_est is K × (K*p + 1): [const | A1 | A2]
        # Julia stores intercept + lag arrays separately
        coefs = coef(model)

        # Intercepts (Python column 0)
        for i in 1:K
            @test coefs.intercept[i] ≈ A_est_py[i, 1] atol=1e-10
        end

        # Lag coefficients: Python A_est[:, 1:K*p+1] vs Julia lags[:,:,lag]
        # Python: A_est[eq, 1 + (lag-1)*K + var-1]
        # Julia: lags[var, eq, lag] — wait, need to check convention
        # In Julia estimation.jl: A[2:end, :] = reshape(lags', (K*p, K))
        # So A[1 + (lag-1)*K + j, i] = lags[j, i, lag] (since lags is n×n×p)
        # Python: A_est[i, 1 + (lag-1)*K + j] (already transposed)
        # lags[eq, var, lag] = coefficient of variable `var` at `lag` in equation `eq`
        for lag in 1:p
            for eq in 1:K
                for var in 1:K
                    py_val = A_est_py[eq, 1 + (lag - 1) * K + var]
                    jl_val = coefs.lags[eq, var, lag]
                    @test jl_val ≈ py_val atol=1e-10
                end
            end
        end
    end

    # ── Test 2: VAR residuals match ───────────────────────────────────────
    @testset "VAR residuals match Python" begin
        @test size(ν_julia) == size(U_est_py)
        for i in 1:K
            @test ν_julia[:, i] ≈ U_est_py[:, i] atol=1e-8
        end
    end

    # ── Test 3: Identification (H1 ratios match) ─────────────────────────
    @testset "Identification: impact ratios match" begin
        # Python: H1 = Σ_um / φ (φ-normalized)
        # Julia: θ with unit effect normalization (θ[1] = 1)
        # Equivalent: θ[i] = H1_py[i] / H1_py[1]
        ratio_py = H1_py[2] / H1_py[1]
        ratio_jl = θ_julia[2] / θ_julia[1]

        @test ratio_jl ≈ ratio_py atol=1e-10
    end

    # ── Test 4: Replicate Python identification formula in Julia ──────────
    @testset "Python identification formula reproduced in Julia" begin
        # Compute Σ_uu and Σ_um the Python way (no df correction)
        m = proxy_py[(p + 1):end]
        Σ_uu_jl = ν_julia' * ν_julia / T_eff
        Σ_um_jl = ν_julia' * m / T_eff

        @test Σ_uu_jl ≈ covUU_py atol=1e-10
        @test Σ_um_jl ≈ covUM_py atol=1e-10

        # φ² = Σ_um' Σ_uu⁻¹ Σ_um
        φ²_jl = dot(Σ_um_jl, Σ_uu_jl \ Σ_um_jl)
        φ_jl = sqrt(φ²_jl)

        @test φ_jl ≈ params["phi"] atol=1e-6

        # H1 = Σ_um / φ
        H1_jl = Σ_um_jl ./ φ_jl

        @test H1_jl ≈ H1_py atol=1e-6
    end

    # ── Test 5: IRFs match ────────────────────────────────────────────────
    @testset "IRFs match Python (normalized)" begin
        n_imp = Int(params["n_imp"])
        irf_result = irf(model, IVIdentification(); horizon = n_imp-1)

        # Python IRF is in H1 scale (φ-normalized)
        # Julia IRF is in unit-effect scale (θ[1]=1)
        # Scale: irf_julia = irf_python / H1_py[1]
        scale = H1_py[1]

        irf_data = Array(irf_result.irf)  # (variable, shock, horizon)
        for h in 0:(n_imp - 1)
            for i in 1:K
                irf_jl = irf_data[i, 1, h + 1]
                irf_py_scaled = irf_py[i, h + 1] / scale

                @test irf_jl ≈ irf_py_scaled atol=1e-4
            end
        end
    end
end
